name: Ejemplo de flujo de trabajo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  mi_trabajo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ejecutar un script
      run: echo Hola Mundo!
